### ISSUE TITLE
Java SDK 9+ XML Issue

### ISSUE THREAD

**Issue by intrepidsilence** [TiBeN/ia-mame#10]
If using the latest JDK (9+) then the required XML libs are no longer available and require that the code be recompiled to manually add the XML libs.

**Comment by TiBeN** [comment]
You are right, since JDK 9, [Modules shared with Java EE are not resolved by default](https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-F640FA9D-FB66-4D85-AD2B-D931174C09A3). I'm planning a bugfix release soon.

**Comment by TiBeN** [comment]
fixed by 642649f

**Comment by tekdope** [comment]
Thx for the fix but despite this new version, still have the same message. 
Am I missing something?

------

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DataBindingException
	at org.tibennetwork.iamame.IaMame.downloadFilesIfNeeded(IaMame.java:187)
	at org.tibennetwork.iamame.IaMame.main(IaMame.java:76)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DataBindingException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

**Comment by TiBeN** [comment]
The binaries have not been released yet. Did you tried by compiling from the master branch ?

**Comment by tekdope** [comment]
Ok, that makes sense then.
I did not compiled it from the branch, just did the classic installation listed in the doc.

**Comment by TiBeN** [comment]
Ok so yes its normal :) I'm planning to release a new version by the weekend. You can track new versions on the [release page](https://github.com/TiBeN/ia-mame/releases).

**Comment by tekdope** [comment]
No worries. Thx man! Appreciate the work on this :)

**Comment by intrepidsilence** [comment]
Thanks for working on this for us!  Cheers!
